default: &default
  adapter: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  su_username: <%= ENV.fetch("POSTGRES_ADMIN_USER") %>
  su_password: <%= ENV.fetch("POSTGRES_ADMIN_PASSWORD") %>
development:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}dev" %>
test:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}test" %>
production:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}prod" %>
