version: '3.7'

networks:
  db:
  traefik:
    name: traefik

services:
  postgres:
    image: docker.pkg.github.com/flexup-dev/sso-general/postgres:latest
    container_name: postgres
    hostname: postgres
    volumes:
      - ${PWD}/tmp/database/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      UID: 1000
      GID: 1000
      DEFAULT_COLLATION: ${DEFAULT_COLLATION:-en_US.UTF-8}
      DEFAULT_CTYPE: ${DEFAULT_CTYPE:-en_US.UTF-8}
      DEFAULT_ENCODING: ${DEFAULT_ENCODING:-UTF8}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-dev}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER:-dev}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-dev}

  redis:
    image: docker.pkg.github.com/flexup-dev/sso-general/redis:5-alpine
    container_name: redis
    hostname: redis
    command: redis-server
    networks:
      - db
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/tmp/database/redis:/data
  web:
    container_name: web
    hostname: web
    depends_on:
      - postgres
      - redis
    networks:
      - db
      - traefik
    build: .
    ports:
      - "3001:3001"
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - $PWD:/project
    environment:
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
      DATABASE_URL: postgres://dev:dev@postgres:5432/project_database_name_
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-dev}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER:-dev}
      RAILS_ENV: ${RAILS_ENV:-development}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-5}
    labels:
      - traefik.docker.network=traefik
      - traefik.http.routers.web-api.rule=Host(`api.docker.localhost`)
      - traefik.http.routers.web-api.entrypoints=http
      - traefik.http.routers.web-apis.rule=Host(`api.docker.localhost`)
      - traefik.http.routers.web-apis.entrypoints=https
      - traefik.http.routers.web-apis.tls=true
      - traefik.http.middlewares.web-api.redirectscheme.scheme=https
      - traefik.http.middlewares.web-api.redirectscheme.permanent=true

