version: '3.7'

networks:
  traefik:
    name: traefik

services:

  test-vue:
    container_name: test-vue
    hostname: test-vue
    networks:
      - traefik
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    labels:
      - traefik.http.routers.home.rule=Host(`vuejs.docker.localhost`)
      - traefik.http.routers.home.entrypoints=http
      - traefik.http.routers.home.middlewares=redirect@file
      - traefik.http.routers.homes.rule=Host(`vuejs.docker.localhost`)
      - traefik.http.routers.homes.entrypoints=https
      - traefik.http.routers.homes.tls=true